version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db_v2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123!
      POSTGRES_DB: warehouse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_v2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin123.com
      PGADMIN_DEFAULT_PASSWORD: Admin123!
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data_v2:/var/lib/pgadmin

volumes:
  postgres_data_v2:
  pgadmin_data_v2:
